#!/usr/bin/env bash
set -euo pipefail

#############################################################################
# Entra Portal - Native Deployment (No Docker Required)
#
# Installs and runs everything directly on the server:
#   - PostgreSQL (via apt)
#   - Node.js 20 (via NodeSource)
#   - Nginx (reverse proxy)
#   - Systemd services for API + agent
#
# Usage: sudo ./scripts/deploy-native.sh
#
# Prerequisites: Debian/Ubuntu server, root access
#############################################################################

INSTALL_DIR="${ENTRA_PORTAL_DIR:-/opt/entra-portal}"
REPO_URL="${ENTRA_PORTAL_REPO:-https://github.com/nikoandreop/entra-portal.git}"
BRANCH="${ENTRA_PORTAL_BRANCH:-main}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${GREEN}[ENTRA]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
err() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

[ "$(id -u)" -eq 0 ] || err "This script must be run as root (use sudo)"

echo -e "${BLUE}"
echo "  ╔═══════════════════════════════════════════╗"
echo "  ║    ENTRA PORTAL - NATIVE DEPLOYMENT       ║"
echo "  ║    MSP Multi-Tenant Entra ID + Intune     ║"
echo "  ╚═══════════════════════════════════════════╝"
echo -e "${NC}"

# ── 1. Install system dependencies ────────────────────────────────────
log "Installing system packages..."
apt-get update -qq
apt-get install -y -qq curl git nginx postgresql postgresql-contrib openssl >/dev/null

# Install Node.js 20 if not present
if ! command -v node &>/dev/null || [[ "$(node -v)" != v20* ]]; then
  log "Installing Node.js 20..."
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash - >/dev/null 2>&1
  apt-get install -y -qq nodejs >/dev/null
fi

log "Node $(node -v), npm $(npm -v), PostgreSQL $(pg_config --version 2>/dev/null || echo 'installed')"

# ── 2. Configure PostgreSQL ───────────────────────────────────────────
log "Setting up PostgreSQL..."
DB_PASS=$(openssl rand -base64 24 | tr -d '\n/+=' | head -c 32)

systemctl enable --now postgresql >/dev/null 2>&1

su - postgres -c "psql -tc \"SELECT 1 FROM pg_roles WHERE rolname='entra'\" | grep -q 1" 2>/dev/null || \
  su - postgres -c "psql -c \"CREATE USER entra WITH PASSWORD '${DB_PASS}';\""

su - postgres -c "psql -tc \"SELECT 1 FROM pg_database WHERE datname='entra_portal'\" | grep -q 1" 2>/dev/null || \
  su - postgres -c "psql -c \"CREATE DATABASE entra_portal OWNER entra;\""

log "PostgreSQL ready (database: entra_portal, user: entra)"

# ── 3. Clone / update code ────────────────────────────────────────────
if [ -d "$INSTALL_DIR/.git" ]; then
  log "Updating existing installation..."
  cd "$INSTALL_DIR"
  git fetch origin "$BRANCH"
  git reset --hard "origin/$BRANCH"
else
  log "Cloning Entra Portal..."
  git clone --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
  cd "$INSTALL_DIR"
fi

# ── 4. Create system user ─────────────────────────────────────────────
id -u entra-portal &>/dev/null || /usr/sbin/useradd --system --home "$INSTALL_DIR" --shell /usr/sbin/nologin entra-portal 2>/dev/null || adduser --system --home "$INSTALL_DIR" --no-create-home --disabled-login entra-portal
chown -R entra-portal:entra-portal "$INSTALL_DIR"

# ── 5. Generate .env ──────────────────────────────────────────────────
if [ ! -f "$INSTALL_DIR/.env" ]; then
  log "Generating .env..."
  JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n/+=' | head -c 64)
  AGENT_SECRET=$(openssl rand -base64 48 | tr -d '\n/+=' | head -c 64)
  ENCRYPTION_KEY=$(openssl rand -base64 24 | tr -d '\n/+=' | head -c 32)
  ADMIN_PASS="EntraAdmin!$(openssl rand -hex 4)"
  SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'localhost')

  cat > "$INSTALL_DIR/.env" << ENVEOF
# Auto-generated by deploy-native.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
JWT_SECRET=${JWT_SECRET}
AGENT_JWT_SECRET=${AGENT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
DEFAULT_ADMIN_PASSWORD=${ADMIN_PASS}

DB_HOST=localhost
DB_PORT=5432
DB_NAME=entra_portal
DB_USER=entra
DB_PASSWORD=${DB_PASS}
DB_POOL_MAX=20

NODE_ENV=production
LOG_LEVEL=info
CORS_ORIGIN=http://${SERVER_IP}
ENVEOF

  chmod 600 "$INSTALL_DIR/.env"
  chown entra-portal:entra-portal "$INSTALL_DIR/.env"
else
  log ".env already exists, keeping current config"
  ADMIN_PASS="(unchanged - see .env)"
fi

# ── 6. Install npm dependencies and build ─────────────────────────────
log "Installing dependencies..."
cd "$INSTALL_DIR"
sudo -u entra-portal npm ci --ignore-scripts 2>/dev/null || sudo -u entra-portal npm install --ignore-scripts

log "Building API..."
sudo -u entra-portal npm run build --workspace=src/shared 2>&1 | tail -1
sudo -u entra-portal npm run build --workspace=src/api 2>&1 | tail -1

log "Building frontend..."
sudo -u entra-portal npm run build --workspace=frontend 2>&1 | tail -1

# ── 7. Deploy frontend to nginx ───────────────────────────────────────
log "Configuring nginx..."
rm -rf /var/www/entra-portal
cp -r "$INSTALL_DIR/frontend/dist" /var/www/entra-portal

cat > /etc/nginx/sites-available/entra-portal << 'NGINXEOF'
server {
    listen 80 default_server;
    server_name _;
    root /var/www/entra-portal;
    index index.html;

    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location /api/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
    }

    location /ws {
        proxy_pass http://127.0.0.1:3002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|svg|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml image/svg+xml;
}
NGINXEOF

rm -f /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/entra-portal /etc/nginx/sites-enabled/
nginx -t && systemctl reload nginx

# ── 8. Create systemd service for API ─────────────────────────────────
log "Creating systemd services..."

cat > /etc/systemd/system/entra-portal-api.service << SVCEOF
[Unit]
Description=Entra Portal API Server
After=network-online.target postgresql.service
Wants=network-online.target
Requires=postgresql.service

[Service]
Type=simple
User=entra-portal
Group=entra-portal
WorkingDirectory=${INSTALL_DIR}
EnvironmentFile=${INSTALL_DIR}/.env
ExecStart=/usr/bin/node ${INSTALL_DIR}/src/api/dist/server.js
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=entra-portal-api

# Hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/log/entra-portal
PrivateTmp=true

[Install]
WantedBy=multi-user.target
SVCEOF

mkdir -p /var/log/entra-portal
chown entra-portal:entra-portal /var/log/entra-portal

systemctl daemon-reload
systemctl enable --now entra-portal-api

# ── 9. Wait for API to start ──────────────────────────────────────────
log "Waiting for API..."
for i in $(seq 1 20); do
  if curl -sf http://localhost:3001/api/health &>/dev/null; then
    break
  fi
  sleep 2
done

# ── 10. Print results ─────────────────────────────────────────────────
SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'localhost')

if curl -sf http://localhost:3001/api/health &>/dev/null; then
  echo ""
  echo -e "${GREEN}════════════════════════════════════════════${NC}"
  echo -e "${GREEN}  Entra Portal is running!${NC}"
  echo -e "${GREEN}════════════════════════════════════════════${NC}"
  echo ""
  echo -e "  Dashboard:  ${BLUE}http://${SERVER_IP}${NC}"
  echo -e "  API:        ${BLUE}http://${SERVER_IP}/api/health${NC}"
  echo ""
  echo -e "  ${YELLOW}Admin credentials (SAVE THESE):${NC}"
  echo -e "    Email:    ${GREEN}admin@entra-portal.local${NC}"
  echo -e "    Password: ${GREEN}${ADMIN_PASS}${NC}"
  echo ""
  echo "  Useful commands:"
  echo "    systemctl status entra-portal-api    # API status"
  echo "    journalctl -u entra-portal-api -f    # API logs"
  echo "    systemctl restart entra-portal-api   # Restart API"
  echo ""
  echo -e "  Auto-updates: ${YELLOW}./scripts/setup-auto-update.sh${NC}"
  echo ""
else
  err "API failed to start. Check: journalctl -u entra-portal-api -n 50"
fi
