#!/usr/bin/env bash
set -euo pipefail

#############################################################################
# Entra Portal - One-Command Server Deployment
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/nikoandreop/entra-portal/main/scripts/deploy.sh | bash
#
# Or clone first:
#   git clone https://github.com/nikoandreop/entra-portal.git
#   cd entra-portal && ./scripts/deploy.sh
#
# Prerequisites: Docker, Docker Compose, Git
#############################################################################

INSTALL_DIR="${ENTRA_PORTAL_DIR:-/opt/entra-portal}"
REPO_URL="${ENTRA_PORTAL_REPO:-https://github.com/nikoandreop/entra-portal.git}"
BRANCH="${ENTRA_PORTAL_BRANCH:-main}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${GREEN}[ENTRA]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
err() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Check prerequisites
for cmd in docker git; do
  command -v "$cmd" &>/dev/null || err "$cmd is required but not installed"
done
docker compose version &>/dev/null || err "Docker Compose v2 is required"

echo -e "${BLUE}"
echo "  ╔═══════════════════════════════════════╗"
echo "  ║       ENTRA PORTAL DEPLOYMENT         ║"
echo "  ║   MSP Multi-Tenant Entra ID + Intune  ║"
echo "  ╚═══════════════════════════════════════╝"
echo -e "${NC}"

# Clone or update repo
if [ -d "$INSTALL_DIR/.git" ]; then
  log "Updating existing installation at $INSTALL_DIR"
  cd "$INSTALL_DIR"
  git fetch origin "$BRANCH"
  git reset --hard "origin/$BRANCH"
else
  log "Cloning Entra Portal to $INSTALL_DIR"
  sudo mkdir -p "$INSTALL_DIR"
  sudo chown "$(id -u):$(id -g)" "$INSTALL_DIR"
  git clone --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
  cd "$INSTALL_DIR"
fi

# Generate .env if not present
if [ ! -f .env ]; then
  log "Generating .env with secure random secrets..."
  JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n/+=' | head -c 64)
  AGENT_SECRET=$(openssl rand -base64 48 | tr -d '\n/+=' | head -c 64)
  ENCRYPTION_KEY=$(openssl rand -base64 24 | tr -d '\n/+=' | head -c 32)
  DB_PASS=$(openssl rand -base64 24 | tr -d '\n/+=' | head -c 32)
  ADMIN_PASS="EntraAdmin!$(openssl rand -hex 4)"

  cat > .env << ENVEOF
# Auto-generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
JWT_SECRET=${JWT_SECRET}
AGENT_JWT_SECRET=${AGENT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
DB_PASSWORD=${DB_PASS}
DEFAULT_ADMIN_PASSWORD=${ADMIN_PASS}

# PostgreSQL
DB_HOST=postgres
DB_PORT=5432
DB_NAME=entra_portal
DB_USER=entra

# Server
NODE_ENV=production
LOG_LEVEL=info
CORS_ORIGIN=http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'localhost'):8080

# Microsoft SSO (optional - uncomment and fill in)
# SSO_TENANT_ID=common
# SSO_CLIENT_ID=
# SSO_CLIENT_SECRET=
# SSO_REDIRECT_URI=http://YOUR_SERVER_IP:8080/auth/callback
ENVEOF

  log "Generated .env with secure secrets"
  echo ""
  echo -e "  ${YELLOW}Admin credentials (SAVE THESE):${NC}"
  echo -e "    Email:    ${GREEN}admin@entra-portal.local${NC}"
  echo -e "    Password: ${GREEN}${ADMIN_PASS}${NC}"
  echo ""
else
  log ".env already exists, keeping current config"
fi

# Build and start
log "Building Docker images..."
docker compose -f docker/docker-compose.yml build --quiet

log "Starting services..."
docker compose -f docker/docker-compose.yml up -d

# Wait for health
log "Waiting for API to become healthy..."
for i in $(seq 1 30); do
  if curl -sf http://localhost:3001/api/health &>/dev/null; then
    break
  fi
  sleep 2
done

if curl -sf http://localhost:3001/api/health &>/dev/null; then
  echo ""
  echo -e "${GREEN}════════════════════════════════════════${NC}"
  echo -e "${GREEN}  Entra Portal is running!${NC}"
  echo -e "${GREEN}════════════════════════════════════════${NC}"
  echo ""
  SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'localhost')
  echo -e "  Dashboard:  ${BLUE}http://${SERVER_IP}:8080${NC}"
  echo -e "  API:        ${BLUE}http://${SERVER_IP}:3001/api/health${NC}"
  echo ""
  echo -e "  To set up auto-updates from GitHub:"
  echo -e "    ${YELLOW}./scripts/setup-auto-update.sh${NC}"
  echo ""
else
  err "API failed to start. Check logs: docker compose -f docker/docker-compose.yml logs api"
fi
